import type { PageLoad } from './$types';

interface PostMeta {
	title: string;
	date: string;
	description: string;
	slug: string;
}

interface VelocityTotals {
	allTime: number;
	core: number;
	docs: number;
	ccli: number;
	since: string;
	trackingBegan: string;
	daysTracked: number;
}

// Import velocity data generated by deploy.sh
import velocityData from '$lib/velocity.json';

export const load: PageLoad = async () => {
	const postFiles = import.meta.glob('/src/content/posts/*.md', { eager: true });

	const posts: PostMeta[] = Object.entries(postFiles).map(([path, module]: [string, any]) => {
		const slug = path.split('/').pop()?.replace('.md', '') || '';
		return {
			title: module.metadata?.title || 'Untitled',
			date: module.metadata?.date || '',
			description: module.metadata?.description || '',
			slug
		};
	});

	// Sort by date descending
	posts.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

	const velocity: VelocityTotals = velocityData;

	return { posts, velocity };
};
